[package]
name = "deltalake-ruby"
version = "0.1.0"
authors = ["R Tyler Croy <rtyler@brokenco.de>"]

[lib]

crate-type = ["cdylib"]

[dependencies]
helix = "*"
tokio = "0.2"

[dependencies.deltalake]
path = "../rust"
