[package]
name = "deltalake-ruby"
version = "0.1.0"
authors = ["R Tyler Croy <rtyler@brokenco.de>"]

[lib]
crate-type = ["cdylib"]

[dependencies]
lazy_static = "1"
rutie = "0.8.2"
tokio = { version = "1", features = ["rt-multi-thread"] }

[dependencies.deltalake]
path = "../rust"
