# frozen_string_literal: true

source 'https://rubygems.org'

gem 'colorize'
gem 'rutie', '~> 0.0.3'

group :development do
  gem 'rake', '~> 12.0'
  gem 'rspec', '~> 3.4'
  gem 'rspec-its', '~> 1.3.0'
end
