# frozen_string_literal: true

require 'bundler/setup'
require 'rspec/core/rake_task'

# For Windows
$stdout.sync = true

RSpec::Core::RakeTask.new(:spec) do |t|
  t.verbose = false
end

task default: :spec
