
coverage:
  status:
    project:
      default:
        # allow some leniency on the deviation of pull requests
        threshold: 1
        if_ci_failed: error
        informational: false
    patch:
      default:
        if_ci_failed: error
        informational: false


ignore:
  - "delta-inspect/"
  - "proofs/"
  - "**/*.toml"
