[default.extend-words]
vAlue = "vAlue"
ValUe = "ValUe"
Alue = "Alue"
Ue = "Ue"
arro3 = "arro3"
arro = "arro"
Arro = "Arro"
Arro3 = "Arro3"
Arro3RecordBatch = "Arro3RecordBatch"
Arro3RecordBatchReader = "Arro3RecordBatchReader"
Arro3DataType = "Arro3DataType"
Arro3Field = "Arro3Field"
Arro3Schema = "Arro3Schema"
AKS = "AKS"
HISTORIAL = "HISTORIAL"

[default]
extend-exclude = [
    "python/docs/source/usage.rst",
    "docs/usage/examining-table.md"
]
