services:
  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    ports:
      - "10000:10000"
      - "10001:10001"
    command:
      - "azurite"
      - "--blobHost"
      - "0.0.0.0"
      - "--loose"

  setup:
    image: mcr.microsoft.com/azure-cli
    depends_on:
      - azurite
    entrypoint: "/bin/bash"
    command:
      - /setup_azurite.sh
    volumes:
      - "./build/setup_azurite.sh:/setup_azurite.sh"
      - "./rust/tests/data/golden:/data/golden"
      - "./rust/tests/data/simple_table:/data/simple_table"
      - "./rust/tests/data/simple_commit:/data/simple_commit"
      - "./rust/tests/data/concurrent_workers:/data/concurrent_workers"
