= delta-rs

image:https://github.com/reiseburo/delta.rs/workflows/build/badge.svg[Build Status,link=https://github.com/reiseburo/delta.rs/actions]
image:https://img.shields.io/crates/v/deltalake.svg?style=flat-square[Crate,link=https://crates.io/crates/deltalake]
image:https://img.shields.io/badge/docs-latest-blue.svg?style=flat-square[Docs,link=https://docs.rs/deltalake]
image:https://img.shields.io/pypi/v/deltalake.svg?style=flat-square[Python binding,link=https://pypi.org/project/deltalake]

An experimental interface to
link:https://delta.io[Delta Lake]
for Rust.

This library provides low level access to Delta tables and is intended to be
used with data processing frameworks like
link:https://github.com/apache/arrow/tree/master/rust/datafusion[datafusion],
link:https://github.com/ballista-compute/ballista[ballista],
link:https://github.com/nevi-me/rust-dataframe[rust-dataframe],
link:https://github.com/rajasekarv/vega[vega], etc.

It can also act as the basis for native bindings in other languages such as Python, Ruby or Golang.

**This project is still very early and only _read_ operations are supported at the moment**.

== Get Involved

Join link:https://join.slack.com/t/delta-users/shared_invite/enQtODQ5ODM5OTAxMjAwLWY4NGI5ZmQ3Y2JmMjZjYjc1MDkwNTA5YTQ4MzhjOWY1MmVjNTM2OGZhNTExNmM5MzQ0YzEzZjIwMjc0OGI0OGM[#delta-rs in the Delta Lake Slack workspace]

=== Development Meeting

We have a standing development sync meeting for those that are interested. The meeting is held every two weeks at **9am PST** on Tuesday mornings. The direct meeting URL is shared in the Slack channel above :point_up: before the meeting.

These meetings are also link:https://www.youtube.com/channel/UCSKhDO79MNcX4pIIRFD0UVg[streamed live via YouTube] if you just want to listen in.

=== Development

Delta.rs requires the Rust compiler, which can be installed with the
link:https://rustup.rs/[rustup]
command.

Running tests can be done with `cargo test`

=== Python

The `python/` directory contains an early prototype of a Python library built on top of delta-rs

=== Ruby

The `ruby/` directory contains an early prototype of a Ruby library built on top of delta-rs
