name: Upload to codecov
inputs:
  token:
    required: true
    type: string
runs:
  using: "composite"
  steps:
    - name: Upload coverage to Codecov
      # https://github.com/codecov/codecov-action/releases/tag/v7.0.0>
      uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f
      with:
        files: codecov.json
        fail_ci_if_error: true
      env:
        CODECOV_TOKEN: ${{ inputs.token }}
