name: Release documentation

on:
  pull_request:
    types:
      - closed
    branches: [main]
    paths:
      - docs/**
      - mkdocs.yml

jobs:
  release-docs:
    if: github.event.pull_request.merged == true
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Trigger the docs release event
        # <https://github.com/peter-evans/repository-dispatch/releases/tag/v4.0.1>
        uses: peter-evans/repository-dispatch@28959ce8df70de7be546dd1250a005dd32156697
        with:
          event-type: release-docs
          client-payload: >
            {
              "tag": "${{ github.ref_name }}"
            }
